[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools>=45",
    "setuptools_scm[toml]>=6.0",
    "cmake-build-extension>=0.3.2",
    "cmake>=3.21.0",
    "ninja",
    "wheel",
]

[project]
name = "pymaat"
description = "Maat - Symbolic execution framework"
readme = "README.md"
requires-python = ">=3.9"
dependencies = []
license = {text = "LGPL-2.1-or-later"}
keywords = ["symbolic-execution", "binary-analysis", "concolic", "emulation", "pcode"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Operating System :: MacOS",
    "Operating System :: POSIX :: Linux", 
    "Programming Language :: C++",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: Implementation :: CPython",
]
dynamic = ["version"]

[project.urls]
Homepage = "https://maat.re"
Changelog = "https://github.com/trailofbits/maat/releases"
Tracker = "https://github.com/trailofbits/issues"
Documentation = "https://maat.re"
Source = "https://github.com/trailofbits/maat"

[dependency-groups]
dev = [
    "build>=1.3.0",
    "pytest>=8.4.1",
]
build = [
    "cmake-build-extension>=0.3.2",
    "cmake>=3.21.0", 
    "ninja",
    "setuptools>=45",
    "setuptools_scm[toml]>=6.0",
    "wheel",
]

[tool.setuptools]
packages = []
py-modules = []

[tool.setuptools_scm]
local_scheme = "dirty-tag"

[tool.cibuildwheel]
build-frontend = "build"
